In [1]:
import pandas as pd
import numpy as np
import xlrd

In [2]:
counts_rates_df = pd.read_excel('/Users/salma/Research/papers/Baltimore_FreddieGray/data/baltimore_final_rates_counts.xlsx')

In [3]:
print(list(counts_rates_df))

['AREA_NEW', 'viocr_index', 'prop_index', 'bseduc_disadv', 'mar_male_disadv', 'Income_disadv', 'disadv_index', 'violent_crime', 'property_crime', 'pop_weight', 'larRP_base', 'burgRP_base', 'arsonRP_base', 'simasRP_base', 'autothefRP_base', 'aggassauRP_base', 'assbythreRP_base', 'robbRP_base', 'murdRP_base', 'shootRP_base', 'sexoffRP_base', 'YEAR', 'BM_COUNT', 'BF_COUNT', 'WM_COUNT', 'WF_COUNT', 'OM_COUNT', 'OF_COUNT', 'FAMOFFBF_COUNT', 'FAMOFFBM_COUNT', 'FAMOFFWF_COUNT', 'FAMOFFWM_COUNT', 'FAMOFFOF_COUNT', 'FAMOFFOM_COUNT', 'DRUGOFFBF_COUNT', 'DRUGOFFBM_COUNT', 'DRUGOFFWF_COUNT', 'DRUGOFFWM_COUNT', 'DRUGOFFOF_COUNT', 'DRUGOFFOM_COUNT', 'SEXOFFBF_COUNT', 'SEXOFFBM_COUNT', 'SEXOFFWF_COUNT', 'SEXOFFWM_COUNT', 'SEXOFFOF_COUNT', 'SEXOFFOM_COUNT', 'DISCONBF_COUNT', 'DISCONBM_COUNT', 'DISCONWF_COUNT', 'DISCONWM_COUNT', 'DISCONOF_COUNT', 'DISCONOM_COUNT', 'WARRBF_COUNT', 'WARRBM_COUNT', 'WARRWF_COUNT', 'WARRWM_COUNT', 'WARROF_COUNT', 'WARROM_COUNT', 'PROPDMBF_COUNT', 'PROPDMBM_COUNT', 'PROPDMWF_COUNT', 'PROPDMWM_COUNT', 'PROPDMOF_COUNT', 'PROPDMOM_COUNT', 'TRAFFBF_COUNT', 'TRAFFBM_COUNT', 'TRAFFWF_COUNT', 'TRAFFWM_COUNT', 'TRAFFOF_COUNT', 'TRAFFOM_COUNT', 'AGGASBF_COUNT', 'AGGASBM_COUNT', 'AGGASWF_COUNT', 'AGGASWM_COUNT', 'AGGASOF_COUNT', 'AGGASOM_COUNT', 'SIMASBF_COUNT', 'SIMASBM_COUNT', 'SIMASWF_COUNT', 'SIMASWM_COUNT', 'SIMASOF_COUNT', 'SIMASOM_COUNT', 'KIDNBF_COUNT', 'KIDNBM_COUNT', 'KIDNWF_COUNT', 'KIDNWM_COUNT', 'KIDNOF_COUNT', 'KIDNOM_COUNT', 'THEFRABF_COUNT', 'THEFRABM_COUNT', 'THEFRAWF_COUNT', 'THEFRAWM_COUNT', 'THEFRAOF_COUNT', 'THEFRAOM_COUNT', 'ATHEFBF_COUNT', 'ATHEFBM_COUNT', 'ATHEFWF_COUNT', 'ATHEFWM_COUNT', 'ATHEFOF_COUNT', 'ATHEFOM_COUNT', 'OTHERBF_COUNT', 'OTHERBM_COUNT', 'OTHERWF_COUNT', 'OTHERWM_COUNT', 'OTHEROF_COUNT', 'OTHEROM_COUNT', 'WEPOBF_COUNT', 'WEPOBM_COUNT', 'WEPOWF_COUNT', 'WEPOWM_COUNT', 'WEPOOF_COUNT', 'WEPOOM_COUNT', 'LARBF_COUNT', 'LARBM_COUNT', 'LARWF_COUNT', 'LARWM_COUNT', 'LAROF_COUNT', 'LAROM_COUNT', 'BURGBF_COUNT', 'BURGBM_COUNT', 'BURGWF_COUNT', 'BURGWM_COUNT', 'BURGOF_COUNT', 'BURGOM_COUNT', 'ROBBBF_COUNT', 'ROBBBM_COUNT', 'ROBBWF_COUNT', 'ROBBWM_COUNT', 'ROBBOF_COUNT', 'ROBBOM_COUNT', 'MURDBF_COUNT', 'MURDBM_COUNT', 'MURDWF_COUNT', 'MURDWM_COUNT', 'MURDOF_COUNT', 'MURDOM_COUNT', 'ARSONBF_COUNT', 'ARSONBM_COUNT', 'ARSONWF_COUNT', 'ARSONWM_COUNT', 'ARSONOF_COUNT', 'ARSONOM_COUNT', 'FamOff_Count', 'FamOff_Count_age1', 'FamOff_Count_age2', 'FamOff_Count_age3', 'FamOff_Count_age4', 'DrugOff_Count', 'DrugOff_Count_age1', 'DrugOff_Count_age2', 'DrugOff_Count_age3', 'DrugOff_Count_age4', 'SexOff_Count', 'SexOff_Count_age1', 'SexOff_Count_age2', 'SexOff_Count_age3', 'SexOff_Count_age4', 'Disorderly_Count', 'Disorderly_Count_age1', 'Disorderly_Count_age2', 'Disorderly_Count_age3', 'Disorderly_Count_age4', 'Warrant_Count', 'Warrant_Count_age1', 'Warrant_Count_age2', 'Warrant_Count_age3', 'Warrant_Count_age4', 'PropertyDmg_Count', 'PropertyDmg_Count_age1', 'PropertyDmg_Count_age2', 'PropertyDmg_Count_age3', 'PropertyDmg_Count_age4', 'Traffic_Count', 'Traffic_Count_age1', 'Traffic_Count_age2', 'Traffic_Count_age3', 'Traffic_Count_age4', 'AggAss_Count', 'AggAss_Count_age1', 'AggAss_Count_age2', 'AggAss_Count_age3', 'AggAss_Count_age4', 'SimpAss_Count', 'SimpAss_Count_age1', 'SimpAss_Count_age2', 'SimpAss_Count_age3', 'SimpAss_Count_age4', 'Kidnap_Count', 'Kidnap_Count_age1', 'Kidnap_Count_age2', 'Kidnap_Count_age3', 'Kidnap_Count_age4', 'TheftFraud_Count', 'TheftFraud_Count_age1', 'TheftFraud_Count_age2', 'TheftFraud_Count_age3', 'TheftFraud_Count_age4', 'AutoTheft_Count', 'AutoTheft_Count_age1', 'AutoTheft_Count_age2', 'AutoTheft_Count_age3', 'AutoTheft_Count_age4', 'Other_Count', 'Other_Count_age1', 'Other_Count_age2', 'Other_Count_age3', 'Other_Count_age4', 'Weapon_Count', 'Weapon_Count_age1', 'Weapon_Count_age2', 'Weapon_Count_age3', 'Weapon_Count_age4', 'Larceny_Count', 'Larceny_Count_age1', 'Larceny_Count_age2', 'Larceny_Count_age3', 'Larceny_Count_age4', 'Burglary_Count', 'Burglary_Count_age1', 'Burglary_Count_age2', 'Burglary_Count_age3', 'Burglary_Count_age4', 'Robbery_Count', 'Robbery_Count_age1', 'Robbery_Count_age2', 'Robbery_Count_age3', 'Robbery_Count_age4', 'Murder_Count', 'Murder_Count_age1', 'Murder_Count_age2', 'Murder_Count_age3', 'Murder_Count_age4', 'Arson_Count', 'Arson_Count_age1', 'Arson_Count_age2', 'Arson_Count_age3', 'Arson_Count_age4', 'age1_total', 'age2_total', 'age3_total', 'age4_total', 'incidentoffense', 'offense_new', 'offense_new2', 'OBJECTID', 'Neighborho', 'Arrest', 'Age', 'Sex', 'Race', 'ArrestDate', 'ArrestTime', 'Charge', 'District', 'Post', 'FID_1', 'OBJECTID_1', 'SUM_Popula', 'SUM_White', 'SUM_Blk_Af', 'SUM_Hisp_L', 'SUM_Male', 'Shape_Leng', 'ChargeDescription', 'IncidentLocation', 'ArrestLocation', 'OFFENSE_NEW1', 'offender_age', 'Nieghborhood', 'AuthoTheft_Count', 'area_count', 'Total_male_pop', 'Tot_female_pop', 'White', 'Black_AfAm', 'Hispanic', 'Tot_non_hisp', 'Med_inc_p12', 'Pop_Total', 'White_Pct', 'Black_Pct', 'Hispanic_Pct', 'Male_Pct', 'Female_Pct', 'young_MalePct', 'young_FemalePct', 'Never_Married_MalePct', 'Never_Married_FemPct', 'Married_MalePct', 'Married_Intact_MalePct', 'Married_Intact_FemPct', 'Married_FemalePct', 'Married_Alone_MalePct', 'Married_Alone_FemPct', 'Female_age25_older', 'Female_age15_to24', 'male_age25_older', 'male_age15_to24', 'age16_oldemp', 'age16_oldemp_Male', 'age16_oldemp_Female', 'Age15_Older', 'Age15_Older_male', 'Age15_Older_Female', 'Age_Median_Male', 'Age_Median_Female', 'Income_med12mo_houshld', 'Income_med12mo_family', 'Income_12mo_houshld', 'Educ_HSGED_MalePct', 'Educ_HSGED_FemalePct', 'Educ_Bachelor_MalePct', 'Educ_Bachelor_FemalePct', 'Educ_Associat_MalePct', 'Educ_Associat_FemalePct', 'Tenure_Housing_Rent', 'Tenure_Housing_Owner', 'Tenure_Housing_All', 'Housing_Vacant', 'Housing_Total', 'Housing_Occupied', 'Houshld_WhitePct', 'Houshld_BlackPct', 'FAMOFFBF_RATE', 'FAMOFFBM_RATE', 'FAMOFFWF_RATE', 'FAMOFFWM_RATE', 'FAMOFFOF_RATE', 'FAMOFFOM_RATE', 'DRUGBF_RATE', 'DRUGBM_RATE', 'DRUGWF_RATE', 'DRUGWM_RATE', 'DRUGOF_RATE', 'DRUGOM_RATE', 'SEXOFFBF_RATE', 'SEXOFFBM_RATE', 'SEXOFFWF_RATE', 'SEXOFFWM_RATE', 'SEXOFFOF_RATE', 'SEXOFFOM_RATE', 'WEPOBF_RATE', 'WEPOBM_RATE', 'WEPOWF_RATE', 'WEPOWM_RATE', 'WEPOOF_RATE', 'WEPOOM_RATE', 'WARRBF_RATE', 'WARRBM_RATE', 'WARRWF_RATE', 'WARRWM_RATE', 'WARROF_RATE', 'WARROM_RATE', 'TRAFFBF_RATE', 'TRAFFBM_RATE', 'TRAFFWF_RATE', 'TRAFFWM_RATE', 'TRAFFOF_RATE', 'TRAFFOM_RATE', 'AGGASBF_RATE', 'AGGASBM_RATE', 'AGGASWF_RATE', 'AGGASWM_RATE', 'AGGASOF_RATE', 'AGGASOM_RATE', 'SIMASBF_RATE', 'SIMASBM_RATE', 'SIMASWF_RATE', 'SIMASWM_RATE', 'SIMASOF_RATE', 'SIMASOM_RATE', 'KIDNBF_RATE', 'KIDNBM_RATE', 'KIDNWF_RATE', 'KIDNWM_RATE', 'KIDNOF_RATE', 'KIDNOM_RATE', 'LARBF_RATE', 'LARBM_RATE', 'LARWF_RATE', 'LARWM_RATE', 'LAROF_RATE', 'LAROM_RATE', 'BURGBF_RATE', 'BURGBM_RATE', 'BURGWF_RATE', 'BURGWM_RATE', 'BURGOF_RATE', 'BURGOM_RATE', 'ROBBBF_RATE', 'ROBBBM_RATE', 'ROBBWF_RATE', 'ROBBWM_RATE', 'ROBBOF_RATE', 'ROBBOM_RATE', 'MURDBF_RATE', 'MURDBM_RATE', 'MURDWF_RATE', 'MURDWM_RATE', 'MURDOF_RATE', 'MURDOM_RATE', 'ARSONBF_RATE', 'ARSONBM_RATE', 'ARSONWF_RATE', 'ARSONWM_RATE', 'ARSONOF_RATE', 'ARSONOM_RATE', 'OTHERBF_RATE', 'OTHERBM_RATE', 'OTHERWF_RATE', 'OTHERWM_RATE', 'OTHEROF_RATE', 'OTHEROM_RATE', 'ATHEFBF_RATE', 'ATHEFBM_RATE', 'ATHEFWF_RATE', 'ATHEFWM_RATE', 'ATHEFOF_RATE', 'ATHEFOM_RATE', 'THEFRABF_RATE', 'THEFRABM_RATE', 'THEFRAWF_RATE', 'THEFRAWM_RATE', 'THEFRAOF_RATE', 'THEFRAOM_RATE', 'DISCONBF_RATE', 'DISCONBM_RATE', 'DISCONWF_RATE', 'DISCONWM_RATE', 'DISCONOF_RATE', 'DISCONOM_RATE', 'PER_YOUNG_AGE', 'PER_BLACK', 'PER_WHITE', 'PER_HISPANIC', 'young_age', 'Other', 'drugtot_rate', 'famtot_rate', 'sextot_rate', 'warrtot_rate', 'wepontot_rate', 'trafftot_rate', 'aggasstot_rate', 'discontot_rate', 'simastot_rate', 'kidtot_rate', 'lartot_rate', 'burgtot_rate', 'robbtot_rate', 'murdtot_rate', 'arsontot_rate', 'autothefttot_rate', 'PER_MALE', 'TOT_OFFENSE_COUNT', 'policy_var', 'TOT_OFF_RATE', 'larRP_count', 'burgRP_count', 'arsonRP_count', 'simasRP_count', 'autothefRP_count', 'aggassauRP_count', 'assbythreRP_count', 'robbRP_count', 'murdRP_count', 'shootRP_count', 'sexoffRP_count', 'CrimeDate', 'CrimeTime', 'CrimeCode', 'Description', 'Neighborhood', 'Total_Inci', 'Description_new', 'larRP_rate', 'burgRP_rate', 'arsonRP_rate', 'simasRP_rate', 'autothefRP_rate', 'aggassauRP_rate', 'assbythreRP_rate', 'robbRP_rate', 'murdRP_rate', 'shootRP_rate', 'sexoffRP_rate', 'per_change_larRP', 'per_change_burgRP', 'per_change_arsonRP', 'per_change_simasRP', 'per_change_autothefRP', 'per_change_aggassauRP', 'per_change_assbythreRP', 'per_change_robbRP', 'per_change_murdRP', 'per_change_shootRP', 'per_change_sexoffRP', 'policy_pas', 'merge_dummy', 'larRP_basemedian', 'burgRP_basemedian', 'arsonRP_basemedian', 'simasRP_basemedian', 'autothefRP_basemedian', 'aggassauRP_basemedian', 'assbythreRP_basemedian', 'robbRP_basemedian', 'murdRP_basemedian', 'shootRP_basemedian', 'sexoffRP_basemedian', 'larRP_rate_level', 'burgRP_level', 'arsonRP_level', 'simasRP_level', 'autothefRP_level', 'aggassauRP_level', 'assbythreRP_level', 'robbRP_level', 'murdRP_level', 'shootRP_level', 'sexoffRP_level', 'larRP_level', 'per_change_larRP_median', 'per_change_burgRP_median', 'per_change_arsonRP_median', 'per_change_simasRP_median', 'per_change_autothefRP_median', 'per_change_aggassauRP_median', 'per_change_assbythreRP_median', 'per_change_robbRP_median', 'per_change_murdRP_median', 'per_change_shootRP_median', 'per_change_sexoffRP_median', 'larRP_rate_trend', 'burgRP_trend', 'arsonRP_trend', 'simasRP_trend', 'autothefRP_trend', 'aggassauRP_trend', 'assbythreRP_trend', 'robbRP_trend', 'murdRP_trend', 'shootRP_trend', 'sexoffRP_trend', 'larRP_trend', 'groupDI']

In [4]:
#### Check for outliers

In [5]:
### viocr_index: -1, 0, 1. Need to check what are the range of values for each of these indices###
counts_rates_df.groupby(['YEAR', 'viocr_index']).agg({'violent_crime':[min, max]})

                 violent_crime
                           min         max
YEAR viocr_index
2013 -1              59.374710  107.540327
      0             119.351101  165.213400
      1             176.395579  585.571012
2014 -1              59.374710  107.540327
      0             119.351101  165.213400
      1             176.395579  585.571012
2015 -1              59.374710  107.540327
      0             119.351101  165.213400
      1             176.395579  585.571012
2016 -1              59.374710  107.540327
      0             119.351101  165.213400
      1             176.395579  585.571012
2017 -1              59.374710  107.540327
      0             119.351101  165.213400
      1             176.395579  585.571012
2018 -1              59.374710  107.540327
      0             119.351101  165.213400
      1             176.395579  585.571012

In [6]:
### prop_index: -1, 0, 1. Need to check what are the range of values for each of these indices###
counts_rates_df.groupby(['YEAR', 'prop_index']).agg({'property_crime':[min, max]})

                property_crime
                           min          max
YEAR prop_index
2013 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2014 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2015 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2016 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2017 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2018 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334

In [7]:
### bseduc_disadv: 1, 2, 3. Need to check what are the range of values for each of these indices###
counts_rates_df.groupby(['YEAR', 'prop_index']).agg({'property_crime':[min, max]})

                property_crime
                           min          max
YEAR prop_index
2013 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2014 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2015 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2016 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2017 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334
2018 -1             229.944675   399.221031
      0             403.797109   601.524730
      1             616.779042  2704.626334